<div class='col-9'>
    <nav aria-label='breadcrumb'>
        <ol class='breadcrumb'>
            <li class='breadcrumb-item'><a href='?action=admin'>Administration</a></li>
            <li class='breadcrumb-item active' aria-current='page'><?php echo htmlspecialchars($insertEditDeck)?></li>
        </ol>
    </nav>

    <h1 class='mx-5 mt-1 fw-bold text-center'><?php echo htmlspecialchars($insertEditDeck)?></h1>
    <form class='mx-5 mt-5' method='post'>
         <div>
            <input type='hidden' name='id' value='<?php echo $oDeck->getId() ?>'>
        </div>
        <div class='mb-3'>
            <label for='title' class='form-label fw-bold px-3'>Nom du deck</label>
            <input 
                type='text' 
                name='title' 
                required 
                class='form-control 
                <?php echo $classError['title']; ?>' 
                value='<?php echo htmlspecialchars($oDeck->getTitle()) ?>'
            >
        </div>


        <button type='submit' class='btn btn-primary my-3'>Envoyer</button>
    </form> 
</div>