
<div class='col-9'>
    <h1 class ='text-center'>Bienvenue</h1>
    <p>Ce site te permet d'organiser des tournois entre amis.</p>
    <p>Si tu es celui qui es toujours désigné pour tenir les scores, l'appli est faite pour toi car en quelques étapes tu peux :</p>
    <ul>
        <li>Créer un championnat</li>
        <li>Y ajouter des joueurs (tes amis trop fainéants pour s'inscrire)</li>
        <li>Leur attribuer des decks</li>
        <li>Créer des matchs et rentrer des résultats</li>
        <li>Profiter de toutes ces statistiques crées, envoyer le lien aux copains</li>
    </ul>
    <a class='nav-link' href='?action=insert_user'>Créer un compte pour commencer</a>

</div>