<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset='UTF-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <title><?php echo $title ?></title>
    <link rel='stylesheet' href='./bootstrap-5/css/bootstrap.css'>
    <link rel='stylesheet' href='./css/style.css'>
</head>
<body>
    <header class='header bg-dark py-5 text-white'>
      <nav class='navbar navbar-expand-lg'>
        <div class='container-fluid'>
          <a class='navbar-brand' href=''>Appli pour Milo</a>
          <button class='navbar-toggler' type='button' data-bs-toggle='collapse' data-bs-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
            <span class='navbar-toggler-icon'></span>
          </button>
          <div class='collapse navbar-collapse' id='navbarSupportedContent'>
            <ul class='navbar-nav me-auto mb-2 mb-lg-0'>
              <li class='nav-item'>
                <a class='nav-link' href=''>V.O.1</a>
              </li>
            </ul>
            <ul class='navbar-nav me-right  mb-2 mb-lg-0'>
              <?php if (isset($_SESSION['id'])) { ?>
                <li class='nav-item'>
                  <a class='nav-link' href='./index.php?action=user&id=<?php echo $_SESSION['id'] ?>'>Mon compte</a>
                </li>
             <?php } ?>
              <li class='nav-item'>
                <a class='nav-link' href='./index.php'>Accueil</a>
              </li>
              <?php if (isset($_SESSION['username']) && ($_SESSION['username']== 'admin')) { ?>
              <li class='nav-item text-white'>
                <a class='nav-link' href='?action=admin'>Administration</a>
              </li>
              <?php } ?>
            </ul>
          </div>
        </div>
      </nav>


    </header>
    <main class='container'>
      <div class='row h-100'>
          <div class='bg-main row col-3 me-1 h-100'>
              <ul class='nav flex-column'>
                  <li class='nav-item'>
                  <a class='nav-link' href='?action=insert_user'>Créer un compte</a>
                  </li>
                  <li class='nav-item'>
                  <a class='nav-link' href='?action=connexion'>Conectez-vous</a>
                  </li>
              </ul>   
          </div>
          <?php include $content . '.phtml' ?>
        </div>
    </main>
    <footer class='footer navbar bottom bg-dark  text-white py-5'>
      <p class='mx-auto'>Formation développeur Web - Gaël Carmona</p>
    </footer>
    <script src='https://kit.fontawesome.com/7d4578f1ad.js' crossorigin='anonymous'></script>
    <script src='bootstrap-5/js/bootstrap.bundle.min.js'></script>
</body>
</html>    

