<div class='col-9'>
    <nav aria-label='breadcrumb'>
        <ol class='breadcrumb'>
            <li class='breadcrumb-item'><a href='?action=admin'>Administration</a></li>
        </ol>
    </nav>
    <p><em><?php echo htmlspecialchars($oUser->getPseudo()) ?></em></p>
    <h1><?php echo htmlspecialchars($oUser->getEmail()) ?></h1><br>
    <p>le <?php echo htmlspecialchars($oUser->getDateCreate()->format('d/m/Y')) ?></p>
    <a class='nav-link' href='?action=edit_user&amp;id=<?php echo intval( $oUser->getId() )?>'>Modifier le compte</a>
    <a class='nav-link' href='?action=disconnect'>Se déconnecter</a>




    <h3 class='mx-5 mt-1 fw-bold text-center'>Mes joueurs</h1>
    <table class='col-12 bg-main'>
        <thead class='text-white bg-dark'>
            <th>ID</th>
            <th>Date de création</th>
            <th>Pseudo</th>
            <th>Modifier</th>
            <th>Supprimer</th>
        </thead>
        <?php
            foreach ($aUsers as $oUser) {?>
                <tr>
                    <td><?php echo intval($oUser->getId()) ?></td>
                    <td><?php echo htmlspecialchars( $oUser->getDateCreate()->format('d/m/Y') )  ?></td>
                    <td><a href='?action=player&amp;id=<?php echo intval($oUser->getId())?>'> <?php echo htmlspecialchars($oUser->getPseudo())?></td>
                    <td><a href='?action=edit_player&amp;id=<?php echo intval( $oUser->getId() )?>'><i class='far fa-edit'></i></a></td>
                    <td><a href='?action=delete_user&amp;id=<?php echo intval( $oUser->getId() )?>'><i class='far fa-trash-alt'></i></a></td>
                </tr>
            <?php } ?>
    </table>
    <a class='nav-link' href='?action=insert_player'>Créer un joueur</a>

    <h3 class='mx-5 mt-1 fw-bold text-center'>Mes championnats</h1>
    <table class='col-12 bg-main'>
        <thead class='text-white bg-dark'>
            <th>ID</th>
            <th>Date de création</th>
            <th>Nom</th>
            <th>Modifier</th>
            <th>Supprimer</th>
        </thead>
        <?php
            foreach ($aChampionships as $oChampionship) {?>
                <tr>
                    <td><?php echo intval($oChampionship->getId()) ?></td>
                    <td><?php echo htmlspecialchars( $oChampionship->getDateCreate()->format('d/m/Y') )  ?></td>
                    <td><a href='?action=championship&amp;championshipId=<?php echo intval($oChampionship->getId())?>'> <?php echo htmlspecialchars($oChampionship->getTitle())?></td>                    
                    <td><a href='?action=edit_championship&amp;id=<?php echo intval( $oChampionship->getId() )?>'><i class='far fa-edit'></i></a></td>
                    <td><a href='?action=delete_championship&amp;id=<?php echo intval( $oChampionship->getId() )?>'><i class='far fa-trash-alt'></i></a></td>
                </tr>
            <?php } ?>
    </table>
    <a class='nav-link' href='?action=insert_championship'>Créer un championnat</a>


    <h3 class='mx-5 mt-1 fw-bold text-center'>Mes decks</h3>
    <table class='col-12 bg-main'>
        <thead class='text-white bg-dark'>
            <th>ID</th>
            <th>Date de création</th>
            <th>Nom</th>
            <th>Modifier</th>
            <th>Supprimer</th>
        </thead>
        <?php 
            foreach ($aDecks as $oDeck) {?>
                <tr>
                    <td><?php echo intval($oDeck->getId()) ?></td>
                    <td><?php echo htmlspecialchars( $oDeck->getDateCreate()->format('d/m/Y') )  ?></td>
                    <td><a href='?action=deck&amp;id=<?php echo intval($oDeck->getId())?>'> <?php echo htmlspecialchars($oDeck->getTitle())?></td>                   
                    <td><a href='?action=edit_deck&amp;id=<?php echo intval( $oDeck->getId() )?>'><i class='far fa-edit'></i></a></td>
                    <td><a href='?action=delete_deck&amp;id=<?php echo intval( $oDeck->getId() )?>'><i class='far fa-trash-alt'></i></a></td>
                </tr>
            <?php } ?>
    </table>
    <a class='nav-link' href='?action=insert_deck&amp;id=<?php echo intval( $_GET['id'] )?>'>Créer un deck</a>

    


</div>